### ISSUE TITLE
tensorflow 2.2, cuda 11 

### ISSUE THREAD

**Issue by darkalexpp** [davidenunes/tensorflow-wheels#10]
Hi,
Maybe you can compile tensorflow 2.2 with cuda 11.0 and cuddn 8.0, cuda compute compatibiliti 5.0. And python 3.8 ?

I use manjaro 20. My cpu use microarchitecture skylake.

**Comment by davidenunes** [comment]
I was just waiting for 2.3 which was just released, are you interested in that one ?

**Comment by darkalexpp** [comment]
Yes, better the version 2.3

**Comment by davidenunes** [comment]
let us see if this compiles x'D

**Comment by davidenunes** [comment]
I'll build it for my compute capability first (6.1) if everything works I'll make another binary for yours (5.0) to avoid putting everything into a huge binary

**Comment by darkalexpp** [comment]
No problem, thank you
Hopefully the new version works well

**Comment by davidenunes** [comment]
The new wheel is already available, the one with compute capability 5.0 is still building, I had to apply a patch for that one, let's see if it works.

**Comment by darkalexpp** [comment]
Thanks, please let me know when it's ready

**Comment by davidenunes** [comment]
done, you can get it from [here](https://github.com/davidenunes/tensorflow-wheels/releases/download/r2.3.cp38.gpu.compute.5/tensorflow-2.3.0-cp38-cp38-linux_x86_64.whl) and test it

**Comment by darkalexpp** [comment]
Thanks, it work fine.
