### ISSUE TITLE
Tensorflow 2.3.0, Ubuntu 20.04 LTS, Cuda 10.1, cuDNN 7.6.5.32, Compute Capability 5.0?

### ISSUE THREAD

**Issue by abhipn** [davidenunes/tensorflow-wheels#11]
Hi @davidenunes,

I have a AMD FX-6100 processor with NVIDIA GTX 750Ti Graphics card which is not supported by TensorFlow 2.3.0. If you compile a wheel which supports my configuration please let me know . Thank you :)

**Comment by davidenunes** [comment]
closing it because I don't have time now to build for this specific platform. If you get me a docker image with all the requirements I can give it a go in my machine.
