### ISSUE TITLE
AVX2 Support on any TF 2.X version.

### ISSUE THREAD

**Issue by salomonMuriel** [davidenunes/tensorflow-wheels#12]
It would be great if you got a build up with AVX2 support for any TF version over 2.0. I tried to build it myself but I can't seem to get it working.

**Comment by davidenunes** [comment]
for which microarchitecture are you trying to make AVX2 work? all my skylake builds were built with AVX2 support, precisely because my CPU supports it, but this might not be the case with other chips:

[CPUs with AVX2](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX2)

**Comment by salomonMuriel** [comment]
Hey, I posted this before installation because the list shows only AVX, but one of the 1.X versions shows both AVX and AVX2 so  I wrongly assumed these builds didn't have AVX2 support.

I installed and tried it and as you said, they do support AVX2. Maybe it would be a good idea to add it to the table just to clear ambiguity since AVX and AVX2 are different instruction sets.

Thanks for creatings these wheels. It saved me a ton of time, I'll be sure to buy you a coffee!

Also, just to let you know, your latest wheel is compatible out of the box with Ubuntu 20.04, but the other ones aren't due to CUDA 10.2 needing nVidia drivers 440.33 but Ubuntu 20.04 comes with drivers 440.100 which are not recognized as compatible with CUDA 10.2 at runtime and are not easily to downgradable, which doesn't let the GPU be visible to Tensorflow. So I think that you could safely add that your latest wheel is fully compatible with 20.04, and the wheels before that are compatible with 18.04, which comes with older drivers.

**Comment by davidenunes** [comment]
I'll make sure to update the information about the wheels and supported instructions.

> So I think that you could safely add that your latest wheel is fully compatible with 20.04, and the wheels before that are compatible with 18.04, which comes with older drivers.

Thanks for the feedback I usually build these in Arch or docker images of the target systems so I didn't go deep on what the compatibility problems were, this helps.

And thanks for your support, coffee is great 👍
