### ISSUE TITLE
TF1.13 CPU no AVX/SSE4.x Py 3.6. Linux x64

### ISSUE THREAD

**Issue by mdsimmo** [davidenunes/tensorflow-wheels#2]
Can I request a tensorflow build with minimal requirements:

Tensorflow: 1.13.?
Python: 3.6
Linux x86_64

No GPU
No AVX
No FMA
No MKL

Cheers,

**Comment by davidenunes** [comment]
yeah sure,

I compiled the latest version (1.13.1) with python 3.6 and no support for GPU or other instructions
https://github.com/davidenunes/tensorflow-wheels/releases/tag/r1.13.1.cp36.cpu

Cheers

**Comment by mdsimmo** [comment]
Awesome, thanks

**Comment by mdsimmo** [comment]
Hi @davidenunes 
I actually tested the wheel today, and it has problems importing because of my glibc version:

    ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)`

I'm running Xubuntu 18.04, but it only has glibc v2.27. Is it possible to get a build using glibc 2.27?

The [glibc releases](https://launchpad.net/ubuntu/bionic/+source/glibc) suggest that the latest version available to any ubuntu distro is 2.27. Did you have to do something special to get version 2.28?

P.S. I don't really understand what I'm talking about, so apologies if I've said something stupid.

**Comment by davidenunes** [comment]
I'm running arch so I have 2.28 for a while now, I can probably try to temporarily downgrade glibc and build against that. I'll try that, give me a couple of minutes

**Comment by davidenunes** [comment]
Wanna give this a try and let me know if it worked?

https://github.com/davidenunes/tensorflow-wheels/releases/tag/r1.13.1.cp26.cpu.glibc227

**Comment by mdsimmo** [comment]
Thanks for quick reply, but still broken with another issue. When importing it gives this response:

    python3: Relink `/lib/x86_64-linux-gnu/libudev.so.1' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
    Segmentation fault (core dumped)

From [this thread](https://github.com/tensorflow/tensorflow/issues/19375), it seems that the problem is due to not installing cudnn properly (which I haven't since I don't have nvidia gpu). Are you sure this is a CPU build? If yes, then I'm lost as to what the problem is.

**Comment by davidenunes** [comment]
There are probably more things mismatching, I should probably relabel the OS to Arch (although it's a rolling distro)
I'll try to build for Ubuntu18.04 which should have the same config as your OS. It will take me a bit more time, but I'll get back to you.

**Comment by mdsimmo** [comment]
No problem, thanks for all your efforts. I've just finished building it on my machine (will release the build soon)

Edit: get the wheel here: https://github.com/yaroslavvb/tensorflow-community-wheels/issues/103

**Comment by davidenunes** [comment]
I didn't consider that we could have more things mismatched between distros, and the dynamic linking could be a problem. I'll make a build image in docker for these occasions. I've been busy downgrading nvidia drivers xD apparently 418 does not play well with TensorFlow :| had to downgrade the kernel as well sigh...

**Comment by davidenunes** [comment]
Done:
[Tensorflow 1.13.1 Python 3.6 Ubuntu 18.04](https://github.com/davidenunes/tensorflow-wheels/releases/download/r1.13.1.cp26.cpu.ubuntu1804/tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl)

I made a docker image to build and test TF for Ubuntu, wanna give the image a try?
I will include this in the list, hopefully now it works :)

**Comment by mdsimmo** [comment]
Failed to run, sorry. On import it just says: `Illegal instruction (core dumped)`
Does the build use AVX or SSE4.x instructions? If so, then the build is probably fine, but my computer is old.

For reference, my -march is `amdfam10` . It supports these flags:
`fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save`

**Comment by davidenunes** [comment]
I built it without any AVX or SSE instructions or CUDA support, but I used the default -march=native options. In order for the build to work for you I need to match your architecture. I should have asked what that was. I built one for amdfam10 for sanity check:
[Tensorflow 1.13.1 Python 3.6 Ubuntu 18.04 amdfam10](
https://github.com/davidenunes/tensorflow-wheels/releases/download/r1.13.1.cp36.cpu.amdfam10/tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl)

**Comment by mdsimmo** [comment]
Works great :)

Note to others trying this: I had to first uninstall tensorflow and everything that depended on tensorflow so that `/usr/local/lib/python3.6/dist-packages` had no more references to tensorflow. Otherwise, parts of old tensorflows would remain and version clashes would occur.

**Comment by davidenunes** [comment]
I recommend using a virtualenv to isolate the environment and install TF inside this env instead of installing globally. To facilitate the virtualenv creation and activation you can use virtualenvwrapper or pipenv. There's also conda,  it manages more than virtualenvs, it also manages other dependencies.

**Comment by l0ophole** [comment]
I have amdfam10 cpu and @mdsimmo 's build for python 2 installs fine for me but his python 3 build gives me an error when I try to install it:

> $ PIP_CONFIG_FILE=/dev/null python -m pip install --isolated --root="/home/loophole/tensorflow" --ignore-installed --verbose --no-deps tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl
Created temporary directory: /tmp/pip-ephem-wheel-cache-ibyuk88j                   Created temporary directory: /tmp/pip-req-tracker-wny4vqzl
Created requirements tracker '/tmp/pip-req-tracker-wny4vqzl'
Created temporary directory: /tmp/pip-install-vufa3ghc
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-wny4vqzl'                              
ERROR: tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 317, in run
    self.populate_requirement_set(
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 281, in populate_requirement_set
    requirement_set.add_requirement(req_to_add)
  File "/usr/lib/python3.8/site-packages/pip/_internal/req/req_set.py", line 89, in add_requirement
    raise InstallationError(
 pip._internal.exceptions.InstallationError: tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.

I also get the same error on @davidenunes 's build (https://github.com/davidenunes/tensorflow-wheels/releases/download/r1.13.1.cp36.cpu.amdfam10/tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl) when I try to install it.
