### ISSUE TITLE
1.14 build for amdfam10 (python3.6) ?

### ISSUE THREAD

**Issue by kahekahe** [davidenunes/tensorflow-wheels#4]
Thanks for sharing these

I'm after a 1.14 build for amdfam10 (python3.6) - do you have one at all?

If not any pointer on how to compile it myself (which compiler options to set) would be helpful.

**Comment by davidenunes** [comment]
Not for 1.14, If I remember correctly all I did to build for amdfam10 was to add the option

> --copt=-march=amdfam10 

to the bazel build command after running config 

> bazel build -c opt --copt=-march=amdfam10 //tensorflow/tools/pip_package:build_pip_package

for the rest I pretty much followed [these instructions](https://www.tensorflow.org/install/source). The only difficulty I encountered building for GPU (I don't know if this is your case) was the fact that the paths for the cuda lib files requested in the ./configure script, required a specific order for the script to find them.

If for some reason you can't build it, I can give it a try when I have the time, just need more details about the target OS etc (to make sure there are no shenanigans with paths of shared libraries etc). I'm assuming you want the CPU version?

**Comment by kahekahe** [comment]
Hi,

I have tried building adding `--copt=-march=amdfam10` but my build fails (I think the system doesn't have sufficient memory to complete it).

I'm looking to run it on Ubuntu 18.04 - cpu version. Would really appreciate it if you are able to build it when you have time?

**Comment by davidenunes** [comment]
ok, let me see what I can do.

**Comment by davidenunes** [comment]
I managed to get some time on my machine to build you a wheel, you can [download and try it](
https://github.com/davidenunes/tensorflow-wheels/releases/download/r1.14.1.cp36.cpu.amdfam10/tensorflow-1.14.1-cp36-cp36m-linux_x86_64.whl) and let me know if it works.

or check the [README](https://github.com/davidenunes/tensorflow-wheels), I added the wheel to the list.

**Comment by kahekahe** [comment]
Just tested, and it works. Thanks very much for this.

Was there anything different about your Bazel configuration? Would be useful to know exactly what you ran for when I need to build a new version in the future.

Thanks again!

**Comment by davidenunes** [comment]
I'm glad I could help, nothing different really, just used the default configuration and run bazel with:

`bazel build -c opt --copt=-march=amdfam10 //tensorflow/tools/pip_package:build_pip_package`

also made sure I had the correct version of bazel, but that was it.
