### ISSUE TITLE
Help with a specific wheel,  tensorflow 1.13.1 SSE running on Ubuntu 18.04, CPU, and Python 3.6

### ISSUE THREAD

**Issue by janus** [davidenunes/tensorflow-wheels#5]
Hello,

I need tensorflow 1.13.1 SSE running on Ubuntu 18.04, CPU, and Python 3.6

**Comment by davidenunes** [comment]
for which cpu type? If it's skylake or similar try [this one ](https://github.com/davidenunes/tensorflow-wheels/releases/download/r1.13.1.cp26.cpu.ubuntu1804/tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl)

**Comment by janus** [comment]
Thanks.
