### ISSUE TITLE
Tensorflow GPU 1.13.2 for Ubuntu 16.04

### ISSUE THREAD

**Issue by gb-savankumar** [davidenunes/tensorflow-wheels#7]
@davidenunes  Hello, 
I need a Tensorflow GPU 1.13.2 wheel file for ubuntu 16.04 which supports CUDA 10.0, cuDNN 7.5. (Without SSE,AVX,FMA) with python 3.5

**Comment by davidenunes** [comment]
closing this, because I didn't have the time back then and don't have any ubuntu environment or image to build them quickly, re-open if still interested, btw the new ubuntu 2 seems to support most of the newer wheels as well
