### ISSUE TITLE
2.1 build for CPU / amdfam10 Python 3.7?

### ISSUE THREAD

**Issue by kahekahe** [davidenunes/tensorflow-wheels#8]
Hi,

Any chance you could provide a 2.1 build for amdfam10 (Python 3.7). I don't seem to be able to get it to build as I only have a limited RAM?

Using Ubuntu 18.04 x86_64 as os.

You kindly built 1.14.1 a while back, but I need to update version for a new project.

**Comment by davidenunes** [comment]
A CPU version is a bit faster for me to build since I don't need to install all the GPU stuff in docker (and I don't have an image ready because I work in Arch), I'll try to build it for you if I have time later on. It seems the new version consumes a ****tone of RAM during the build process, so I'm not surprised.

**Comment by davidenunes** [comment]
here you go:
[download](https://github.com/davidenunes/tensorflow-wheels/releases/download/r2.1.cp37.cpu.amdfam10/tensorflow-2.1.0-cp37-cp37m-linux_x86_64.whl)

**Comment by kahekahe** [comment]
Thanks for this. It doesn't seem to work on my system though.

Seems strange as the last build that you did `1.14.1` worked perfectly.

with the wheel installed in `venv_ml` I'm getting `Illegal instruction (core dumped)`:

```python
(venv_ml) ubuntu@ub18:~/Projects/ml-tests/app$ python3 --version
Python 3.7.7

(venv_ml) ubuntu@ub18:~/Projects/ml-tests/app$ python3 -c 'import tensorflow; print(tensorflow.__version__)'
Illegal instruction (core dumped)
```



The machine info is as follows:

```
(venv_ml) ubuntu@ub18:~/Projects/ml-tests/app$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

(venv_ml) ubuntu@ub18:~/Projects/ml-tests/app$ cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 18
model		: 1
model name	: AMD A6-3650 APU with Radeon(tm) HD Graphics
stepping	: 0
microcode	: 0x3000027
cpu MHz		: 1821.845
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 6
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips	: 5199.92
TLB size	: 1536 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

```

**Comment by davidenunes** [comment]
I might have built it with some instructions that you don't have, thanks for the info, I'll get back to you

**Comment by davidenunes** [comment]
closing this, because I didn't have the time back then and a couple of releases came out recently, re-open if interested in newer version
