### ISSUE TITLE
I need tensor flow with cuda Compute Capability 5.0

### ISSUE THREAD

**Issue by darkalexpp** [davidenunes/tensorflow-wheels#9]
when i execute code, i have:
Ignoring visible gpu device (device: 0, name: GeForce 940M, pci bus id: 0000:01:00.0, compute capability: 5.0) with Cuda compute capability 5.0. The minimum required Cuda capability is 6.1.

i need compile tensorflow 2.2.0, python 3.8.2, cuda 10.2, cudnn 7.6, nccl 2.6 and Compute Capability 5.0
TF_CUDA_COMPUTE_CAPABILITIES=5.0

**Comment by davidenunes** [comment]
for which OS and instruction set? my default is archlinux and skylake, if you want anything different, I'm afraid it would take more time since I need to get some environment that matches your specs, and my hands are a bit full at the moment, otherwise, I can get a build in a couple of hours.

**Comment by davidenunes** [comment]
Alternatively, if you already have a docker image with your matching system and everything installed, it would also be faster for me to build for it since I would just need to change the CUDA compatibility.

**Comment by darkalexpp** [comment]
I have everything installed, and my OS is compatible.
I just need change the cuda compatibility to 5.0

**Comment by davidenunes** [comment]
so you used one of my archlinux wheels and it works with your setup is that it? In that case, I just need to know which python version you're using

**Comment by darkalexpp** [comment]
Yes, i install the tensorflow 2.2 for archlinux and this work.
I use python 3.8

**Comment by davidenunes** [comment]
alright nice, in that case, give me a couple of hours.

**Comment by davidenunes** [comment]
try [this one](https://github.com/davidenunes/tensorflow-wheels/releases/download/r2.2.cp38.gpu.cuda5/tensorflow-2.2.0-cp38-cp38-linux_x86_64.whl) and let me know

**Comment by darkalexpp** [comment]
thanks you, this wheel works fine!

i use ubuntu 20.04
